language: node_js
node_js: "stable"

dist: trusty
sudo: required

addons:
  chrome: stable

before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
  - node server/index.js > server.txt & 

services:
  - mongodb

install:
  - cd jiff && npm install && cd ..
  - npm install

script:
  - npm test
