language: node_js
node_js: "stable"

dist: trusty
sudo: required

addons:
  chrome: stable
  apt:
    packages:
      - fluxbox

before_install:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
  #- google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - fluxbox >/dev/null 2>&1 &
  - node server/index.js > server.txt & 

services:
  - mongodb
  - xvfb

install:
  - cd jiff && npm install && cd ..
  - npm install

script:
  - travis_wait 30 npm test
